-- ===========================================================
-- Baltimore Metal Crafters Database (Postgres / Supabase)
-- Postgres Schema for Supabase (DEV/PROD)
-- ===========================================================

-- NOTE:
-- - Remove any MySQL-specific syntax (USE, ENUM, AUTO_INCREMENT, DATETIME)
-- - Identity columns use GENERATED BY DEFAULT AS IDENTITY
-- - ENUMs replaced with TEXT + CHECK constraints for portability
-- - Timestamps use TIMESTAMP WITH TIME ZONE where appropriate

-- ===========================================================
-- 1. CUSTOMER
-- ===========================================================
CREATE TABLE IF NOT EXISTS customer (
  customer_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name             VARCHAR(100) NOT NULL,
  phone            VARCHAR(30),
  email            VARCHAR(100),
  address          VARCHAR(255)
);

-- ===========================================================
-- 2. EMPLOYEE
-- ===========================================================
CREATE TABLE IF NOT EXISTS employee (
  employee_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name             VARCHAR(100) NOT NULL,
  role             TEXT NOT NULL CHECK (role IN ('restorer','fabricator','admin')),
  specialization   VARCHAR(100),
  contact_info     VARCHAR(150),
  hourly_rate      DECIMAL(10,2) DEFAULT 0.00
);

-- ===========================================================
-- 3. QUOTE / QUOTE ITEM
-- ===========================================================
CREATE TABLE IF NOT EXISTS quote (
  quote_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id      INTEGER NOT NULL,
  date_created     DATE DEFAULT CURRENT_DATE,
  total_estimate   DECIMAL(10,2),
  approved         BOOLEAN DEFAULT FALSE,
  notes            TEXT,
  CONSTRAINT fk_quote_customer FOREIGN KEY (customer_id) REFERENCES customer(customer_id)
);

CREATE TABLE IF NOT EXISTS quoteitem (
  quote_item_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quote_id         INTEGER NOT NULL,
  description      VARCHAR(255),
  est_labor_cost   DECIMAL(10,2),
  est_material_cost DECIMAL(10,2),
  CONSTRAINT fk_quoteitem_quote FOREIGN KEY (quote_id) REFERENCES quote(quote_id)
);

-- ===========================================================
-- 4. JOB / STAGES / NOTES / PHOTOS
-- ===========================================================
CREATE TABLE IF NOT EXISTS job (
  job_id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id      INTEGER NOT NULL,
  quote_id         INTEGER,
  description      VARCHAR(255),
  start_date       DATE,
  due_date         DATE,
  status           TEXT DEFAULT 'Planned' CHECK (status IN ('Planned','InProgress','Completed')),
  CONSTRAINT fk_job_customer FOREIGN KEY (customer_id) REFERENCES customer(customer_id),
  CONSTRAINT fk_job_quote FOREIGN KEY (quote_id) REFERENCES quote(quote_id)
);

CREATE TABLE IF NOT EXISTS jobstage (
  stage_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id           INTEGER NOT NULL,
  stage_name       VARCHAR(50),
  start_date       DATE,
  end_date         DATE,
  CONSTRAINT fk_jobstage_job FOREIGN KEY (job_id) REFERENCES job(job_id)
);

CREATE TABLE IF NOT EXISTS notes (
  note_id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id           INTEGER NOT NULL,
  note_text        TEXT,
  created_at       TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_notes_job FOREIGN KEY (job_id) REFERENCES job(job_id)
);

CREATE TABLE IF NOT EXISTS photo (
  photo_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id           INTEGER NOT NULL,
  file_path        VARCHAR(255),
  description      VARCHAR(255),
  CONSTRAINT fk_photo_job FOREIGN KEY (job_id) REFERENCES job(job_id)
);

-- ===========================================================
-- 5. MATERIAL / JOBMATERIAL
-- ===========================================================
CREATE TABLE IF NOT EXISTS vendor (
  vendor_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name             VARCHAR(100) NOT NULL,
  contact_info     VARCHAR(150),
  phone            VARCHAR(30),
  email            VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS material (
  material_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name             VARCHAR(100) NOT NULL,
  category         VARCHAR(100),
  stock_quantity   INTEGER DEFAULT 0,
  reorder_level    INTEGER DEFAULT 5,
  unit_cost        DECIMAL(10,2),
  vendor_id        INTEGER,
  CONSTRAINT fk_material_vendor FOREIGN KEY (vendor_id) REFERENCES vendor(vendor_id)
);

CREATE TABLE IF NOT EXISTS jobmaterial (
  job_id           INTEGER NOT NULL,
  material_id      INTEGER NOT NULL,
  quantity_used    INTEGER DEFAULT 1,
  PRIMARY KEY (job_id, material_id),
  CONSTRAINT fk_jobmaterial_job FOREIGN KEY (job_id) REFERENCES job(job_id),
  CONSTRAINT fk_jobmaterial_material FOREIGN KEY (material_id) REFERENCES material(material_id)
);

-- ===========================================================
-- 6. PURCHASE ORDER / PO ITEM
-- ===========================================================
CREATE TABLE IF NOT EXISTS purchaseorder (
  po_id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vendor_id        INTEGER NOT NULL,
  order_date       DATE DEFAULT CURRENT_DATE,
  total_cost       DECIMAL(10,2),
  status           TEXT DEFAULT 'Pending' CHECK (status IN ('Pending','Received','Cancelled')),
  CONSTRAINT fk_po_vendor FOREIGN KEY (vendor_id) REFERENCES vendor(vendor_id)
);

CREATE TABLE IF NOT EXISTS poitem (
  po_item_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  po_id            INTEGER NOT NULL,
  material_id      INTEGER NOT NULL,
  quantity         INTEGER DEFAULT 1,
  unit_price       DECIMAL(10,2),
  CONSTRAINT fk_poitem_po FOREIGN KEY (po_id) REFERENCES purchaseorder(po_id),
  CONSTRAINT fk_poitem_material FOREIGN KEY (material_id) REFERENCES material(material_id)
);

-- ===========================================================
-- 7. INVOICE / PAYMENT / SHIPMENT
-- ===========================================================
CREATE TABLE IF NOT EXISTS invoice (
  invoice_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id           INTEGER NOT NULL,
  invoice_date     DATE DEFAULT CURRENT_DATE,
  total_amount     DECIMAL(10,2),
  paid             BOOLEAN DEFAULT FALSE,
  CONSTRAINT fk_invoice_job FOREIGN KEY (job_id) REFERENCES job(job_id)
);

CREATE TABLE IF NOT EXISTS payment (
  payment_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id       INTEGER NOT NULL,
  payment_date     DATE DEFAULT CURRENT_DATE,
  amount           DECIMAL(10,2),
  method           TEXT CHECK (method IN ('Cash','Card','Check','Other')),
  CONSTRAINT fk_payment_invoice FOREIGN KEY (invoice_id) REFERENCES invoice(invoice_id)
);

CREATE TABLE IF NOT EXISTS shipment (
  shipment_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id           INTEGER NOT NULL,
  ship_date        DATE,
  carrier          VARCHAR(100),
  tracking_number  VARCHAR(100),
  CONSTRAINT fk_shipment_job FOREIGN KEY (job_id) REFERENCES job(job_id)
);

-- ===========================================================
-- 8. WORK LOG
-- ===========================================================
CREATE TABLE IF NOT EXISTS worklog (
  worklog_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id           INTEGER NOT NULL,
  employee_id      INTEGER NOT NULL,
  stage_id         INTEGER,
  hours_worked     DECIMAL(5,2),
  work_date        DATE DEFAULT CURRENT_DATE,
  CONSTRAINT fk_worklog_job FOREIGN KEY (job_id) REFERENCES job(job_id),
  CONSTRAINT fk_worklog_employee FOREIGN KEY (employee_id) REFERENCES employee(employee_id),
  CONSTRAINT fk_worklog_stage FOREIGN KEY (stage_id) REFERENCES jobstage(stage_id)
);
